//
// CheckBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CheckBody: Codable {

    /** Идентификатор Whatsapp ID */
    public var whatsappID: String?
    /** Номер в формате 79999999999 */
    public var number: String?

    public init(whatsappID: String? = nil, number: String? = nil) {
        self.whatsappID = whatsappID
        self.number = number
    }

    public enum CodingKeys: String, CodingKey { 
        case whatsappID = "WhatsappID"
        case number
    }

}
