//
// GetchatsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetchatsBody: Codable {

    /** Идентификатор Whatsapp ID */
    public var whatsappID: String?

    public init(whatsappID: String? = nil) {
        self.whatsappID = whatsappID
    }

    public enum CodingKeys: String, CodingKey { 
        case whatsappID = "WhatsappID"
    }

}
