//
// GetmediaBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetmediaBody: Codable {

    /** Идентификатор Whatsapp ID */
    public var whatsappID: String?
    /** Идентификатор медиафайла, содержится во входящих сообщениях. */
    public var mediaKey: String?

    public init(whatsappID: String? = nil, mediaKey: String? = nil) {
        self.whatsappID = whatsappID
        self.mediaKey = mediaKey
    }

    public enum CodingKeys: String, CodingKey { 
        case whatsappID = "WhatsappID"
        case mediaKey
    }

}
