//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var result: OneOfinlineResponse200Result?

    public init(result: OneOfinlineResponse200Result? = nil) {
        self.result = result
    }


}
