//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003: Codable {

    /** при удачном исполнении запроса содержит OK */
    public var result: String?
    public var media: Media?

    public init(result: String? = nil, media: Media? = nil) {
        self.result = result
        self.media = media
    }


}
