//
// InlineResponse2002.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002: Codable {

    /** при удачном исполнении запроса содержит OK */
    public var result: String?
    /** массив объектов ResponseChat */
    public var data: [ResponseChat]?

    public init(result: String? = nil, data: [ResponseChat]? = nil) {
        self.result = result
        self.data = data
    }


}
