//
// InlineResponse2004.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004: Codable {

    /** при удачном исполнении запроса содержит OK */
    public var result: String?

    public init(result: String? = nil) {
        self.result = result
    }


}
