//
// InlineResponse2001.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001: Codable {

    /** при удачном исполнении запроса содержит OK */
    public var result: String?
    /** результат проверки, true - зарегистрирован. */
    public var data: Bool?

    public init(result: String? = nil, data: Bool? = nil) {
        self.result = result
        self.data = data
    }


}
