//
// MessageText.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageText: Codable {

    public enum ModelType: String, Codable { 
        case text = "text"
    }
    public var body: String
    public var quote: String?
    public var type: ModelType?

    public init(body: String, quote: String? = nil, type: ModelType? = nil) {
        self.body = body
        self.quote = quote
        self.type = type
    }


}
