//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelError: Codable {

    /** Наименование ошибки */
    public var name: String?
    /** Текст ошибки */
    public var message: String?
    public var code: Int?
    public var status: Int?

    public init(name: String? = nil, message: String? = nil, code: Int? = nil, status: Int? = nil) {
        self.name = name
        self.message = message
        self.code = code
        self.status = status
    }


}
