//
// ResponseChatGroupMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Метаданные группы, если чат является группой */

public struct ResponseChatGroupMetadata: Codable {

    /** Идентификатор группы в формате WhatsApp */
    public var _id: String?
    /** Дата создания группы в формате Unix Time Stamp */
    public var creation: Int?
    /** Идентификатор создателя группы в формате WhatsApp */
    public var owner: String?
    /** Количество участников в группе */
    public var size: Int?
    /** Массив участников */
    public var participants: [ResponseChatGroupMetadataParticipants]?

    public init(_id: String? = nil, creation: Int? = nil, owner: String? = nil, size: Int? = nil, participants: [ResponseChatGroupMetadataParticipants]? = nil) {
        self._id = _id
        self.creation = creation
        self.owner = owner
        self.size = size
        self.participants = participants
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case creation
        case owner
        case size
        case participants
    }

}
