//
// ResponseChat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseChat: Codable {

    /** Идентификатор контакта или группы в формате WhatsApp */
    public var _id: String?
    /** Имя контакта или группы */
    public var name: String?
    /** Является ли чат контактом или группой */
    public var isGroup: Bool?
    /** Является ли чат ReadOnly */
    public var isReadOnly: Bool?
    /** Количество непрочитанных сообщений в чате */
    public var unreadCount: Int?
    /** Время последней активночти в чате */
    public var timestamp: Int?
    /** Является ли чат закрепленным */
    public var pinned: Bool?
    /** Выключен ли у чата звук */
    public var isMuted: Bool?
    /** Время, оставшееся до включения звука */
    public var muteExpiration: Bool?
    public var groupMetadata: ResponseChatGroupMetadata?

    public init(_id: String? = nil, name: String? = nil, isGroup: Bool? = nil, isReadOnly: Bool? = nil, unreadCount: Int? = nil, timestamp: Int? = nil, pinned: Bool? = nil, isMuted: Bool? = nil, muteExpiration: Bool? = nil, groupMetadata: ResponseChatGroupMetadata? = nil) {
        self._id = _id
        self.name = name
        self.isGroup = isGroup
        self.isReadOnly = isReadOnly
        self.unreadCount = unreadCount
        self.timestamp = timestamp
        self.pinned = pinned
        self.isMuted = isMuted
        self.muteExpiration = muteExpiration
        self.groupMetadata = groupMetadata
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case isGroup
        case isReadOnly
        case unreadCount
        case timestamp
        case pinned
        case isMuted
        case muteExpiration
        case groupMetadata
    }

}
