//
// ResponseMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResponseMessage: Codable {

    /** Идентификатор сообщения */
    public var _id: String?
    /** Флаг просмотра сообщения */
    public var ack: Int?
    /** Флаг, имеет ли сообщение медиафайл */
    public var hasMedia: Bool?
    /** Ключ медиафайла (при наличии) */
    public var mediaKey: String?
    /** Текст сообщения */
    public var body: String?
    /** Тип сообщения */
    public var type: String?
    /** Время сообщения в формате Unix Timestamp */
    public var timestamp: Int?
    /** Идентификатор отправителя в формате WhatsApp */
    public var from: String?
    /** Идентификатор получателя в формате WhatsApp */
    public var to: String?
    /** Флаг, было ли сообщение перенаправлено */
    public var isForwarded: Bool?

    public init(_id: String? = nil, ack: Int? = nil, hasMedia: Bool? = nil, mediaKey: String? = nil, body: String? = nil, type: String? = nil, timestamp: Int? = nil, from: String? = nil, to: String? = nil, isForwarded: Bool? = nil) {
        self._id = _id
        self.ack = ack
        self.hasMedia = hasMedia
        self.mediaKey = mediaKey
        self.body = body
        self.type = type
        self.timestamp = timestamp
        self.from = from
        self.to = to
        self.isForwarded = isForwarded
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case ack
        case hasMedia
        case mediaKey
        case body
        case type
        case timestamp
        case from
        case to
        case isForwarded
    }

}
