//
// SeenBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SeenBody: Codable {

    /** Идентификатор Whatsapp ID */
    public var whatsappID: String?
    public var recipient: AnyOfseenBodyRecipient?

    public init(whatsappID: String? = nil, recipient: AnyOfseenBodyRecipient? = nil) {
        self.whatsappID = whatsappID
        self.recipient = recipient
    }

    public enum CodingKeys: String, CodingKey { 
        case whatsappID = "WhatsappID"
        case recipient
    }

}
