//
// _API.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class _API {
    /**
     Возвращает объект медиафайла, прикрепленного к сообщению

     - parameter body: (body) Запрашивает и возвращает медиа-файл, прикрепленный к сообщению по идентификатору mediaKey. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getMediaPost(body: GetmediaBody, completion: @escaping ((_ data: InlineResponse2003?,_ error: Error?) -> Void)) {
        getMediaPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Возвращает объект медиафайла, прикрепленного к сообщению
     - POST /get-media
     - 

     - API Key:
       - type: apiKey X-API-Key 
       - name: ApiKeyAuth
     - examples: [{contentType=application/json, example={
  "result" : "result",
  "media" : {
    "filename" : "filename",
    "data" : "data",
    "mimetype" : "application/ogg"
  }
}}]
     - parameter body: (body) Запрашивает и возвращает медиа-файл, прикрепленный к сообщению по идентификатору mediaKey. 

     - returns: RequestBuilder<InlineResponse2003> 
     */
    open class func getMediaPostWithRequestBuilder(body: GetmediaBody) -> RequestBuilder<InlineResponse2003> {
        let path = "/get-media"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<InlineResponse2003>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
